# Generated by Django 2.2 on 2020-02-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('weight_unit', models.CharField(choices=[('kg', 'kilograme'), ('Ibs', 'Pounds')], max_length=250)),
                ('height', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('bmi', models.CharField(max_length=250)),
                ('blood_glucose_level', models.CharField(max_length=250)),
                ('last_clinic_visit', models.DateTimeField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
            options={
                'db_table': 'biodata',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_manifestations', models.TextField()),
                ('diagnosis', models.CharField(max_length=250)),
                ('prescription', models.CharField(max_length=250)),
                ('next_appointment', models.DateTimeField()),
                ('doctor_seen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='authentication.Profile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='authentication.Profile')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
