# Generated by Django 2.2 on 2020-02-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0004_auto_20200224_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='allergies',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='biodata',
            name='diabilities',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
