# Generated by Django 2.2 on 2020-02-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0005_auto_20200224_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='diabilities',
            new_name='disabilities',
        ),
    ]
