# Generated by Django 2.2 on 2020-02-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0006_auto_20200224_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='last_clinic_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
