# Generated by Django 2.2 on 2020-02-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0007_auto_20200225_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='status',
            field=models.CharField(default='Good', max_length=200),
        ),
    ]
