# Generated by Django 2.2 on 2020-02-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0008_biodata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('lethality', models.CharField(choices=[('serious', 'serious'), ('moderate', 'moderate'), ('terminal', 'terminal')], max_length=150)),
            ],
        ),
    ]
