# Generated by Django 2.2 on 2020-02-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehealth', '0010_auto_20200225_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_seen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='authentication.MedicalPractitioner'),
        ),
    ]
