# Generated by Django 2.2 on 2020-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='patient_id',
        ),
    ]
