# Generated by Django 2.2 on 2020-02-24 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_remove_profile_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPractitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=250)),
                ('number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profilepictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'active'), ('pending', 'pending')], max_length=250)),
                ('otp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.OTP')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicalpractitioner',
                'ordering': ['-created_at'],
            },
        ),
    ]
