# Generated by Django 2.2 on 2020-02-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_medicalpractitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Good', max_length=200),
        ),
    ]
